//*
// CAN service.
//
// Service that enables a control of the CAN features of device

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: CanService.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusStates int32

const (
	BusStates_ERROR_ACTIVE  BusStates = 0
	BusStates_ERROR_WARNING BusStates = 1
	BusStates_ERROR_PASSIVE BusStates = 2
	BusStates_BUS_OFF       BusStates = 3
	BusStates_STOPPED       BusStates = 4
	BusStates_SLEEPING      BusStates = 5
)

// Enum value maps for BusStates.
var (
	BusStates_name = map[int32]string{
		0: "ERROR_ACTIVE",
		1: "ERROR_WARNING",
		2: "ERROR_PASSIVE",
		3: "BUS_OFF",
		4: "STOPPED",
		5: "SLEEPING",
	}
	BusStates_value = map[string]int32{
		"ERROR_ACTIVE":  0,
		"ERROR_WARNING": 1,
		"ERROR_PASSIVE": 2,
		"BUS_OFF":       3,
		"STOPPED":       4,
		"SLEEPING":      5,
	}
)

func (x BusStates) Enum() *BusStates {
	p := new(BusStates)
	*p = x
	return p
}

func (x BusStates) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BusStates) Descriptor() protoreflect.EnumDescriptor {
	return file_CanService_proto_enumTypes[0].Descriptor()
}

func (BusStates) Type() protoreflect.EnumType {
	return &file_CanService_proto_enumTypes[0]
}

func (x BusStates) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BusStates.Descriptor instead.
func (BusStates) EnumDescriptor() ([]byte, []int) {
	return file_CanService_proto_rawDescGZIP(), []int{0}
}

// Request to set transceiver power
type SetTransceiverPowerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interfaceName,proto3" json:"interfaceName,omitempty"` // e.g., "CAN1"
	PowerOn       bool                   `protobuf:"varint,2,opt,name=powerOn,proto3" json:"powerOn,omitempty"`            // true to power on, false to power off
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTransceiverPowerRequest) Reset() {
	*x = SetTransceiverPowerRequest{}
	mi := &file_CanService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTransceiverPowerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTransceiverPowerRequest) ProtoMessage() {}

func (x *SetTransceiverPowerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CanService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTransceiverPowerRequest.ProtoReflect.Descriptor instead.
func (*SetTransceiverPowerRequest) Descriptor() ([]byte, []int) {
	return file_CanService_proto_rawDescGZIP(), []int{0}
}

func (x *SetTransceiverPowerRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *SetTransceiverPowerRequest) GetPowerOn() bool {
	if x != nil {
		return x.PowerOn
	}
	return false
}

// Request to enable or disable termination
type SetTerminationRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName     string                 `protobuf:"bytes,1,opt,name=interfaceName,proto3" json:"interfaceName,omitempty"`          // e.g., "CAN1"
	EnableTermination bool                   `protobuf:"varint,2,opt,name=enableTermination,proto3" json:"enableTermination,omitempty"` // true to enable, false to disable
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SetTerminationRequest) Reset() {
	*x = SetTerminationRequest{}
	mi := &file_CanService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTerminationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTerminationRequest) ProtoMessage() {}

func (x *SetTerminationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CanService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTerminationRequest.ProtoReflect.Descriptor instead.
func (*SetTerminationRequest) Descriptor() ([]byte, []int) {
	return file_CanService_proto_rawDescGZIP(), []int{1}
}

func (x *SetTerminationRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *SetTerminationRequest) GetEnableTermination() bool {
	if x != nil {
		return x.EnableTermination
	}
	return false
}

// Request to list available CAN interfaces
type ListInterfacesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterfacesRequest) Reset() {
	*x = ListInterfacesRequest{}
	mi := &file_CanService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterfacesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfacesRequest) ProtoMessage() {}

func (x *ListInterfacesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CanService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterfacesRequest.ProtoReflect.Descriptor instead.
func (*ListInterfacesRequest) Descriptor() ([]byte, []int) {
	return file_CanService_proto_rawDescGZIP(), []int{2}
}

// Response containing the list of CAN interfaces
type ListInterfacesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interfaces    []string               `protobuf:"bytes,1,rep,name=interfaces,proto3" json:"interfaces,omitempty"` // List of available interface names (e.g., ["CAN1", "CAN2"])
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInterfacesResponse) Reset() {
	*x = ListInterfacesResponse{}
	mi := &file_CanService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInterfacesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInterfacesResponse) ProtoMessage() {}

func (x *ListInterfacesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CanService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInterfacesResponse.ProtoReflect.Descriptor instead.
func (*ListInterfacesResponse) Descriptor() ([]byte, []int) {
	return file_CanService_proto_rawDescGZIP(), []int{3}
}

func (x *ListInterfacesResponse) GetInterfaces() []string {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

// Genereric request containing the name of the interface
type GetInterfaceNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interfaceName,proto3" json:"interfaceName,omitempty"` // e.g., "CAN1"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInterfaceNameRequest) Reset() {
	*x = GetInterfaceNameRequest{}
	mi := &file_CanService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterfaceNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterfaceNameRequest) ProtoMessage() {}

func (x *GetInterfaceNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CanService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterfaceNameRequest.ProtoReflect.Descriptor instead.
func (*GetInterfaceNameRequest) Descriptor() ([]byte, []int) {
	return file_CanService_proto_rawDescGZIP(), []int{4}
}

func (x *GetInterfaceNameRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

// Response containing power status of a CAN transceiver
type GetTransceiverPowerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PowerOn       bool                   `protobuf:"varint,1,opt,name=powerOn,proto3" json:"powerOn,omitempty"` // true if enabled, otherwise false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransceiverPowerResponse) Reset() {
	*x = GetTransceiverPowerResponse{}
	mi := &file_CanService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransceiverPowerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransceiverPowerResponse) ProtoMessage() {}

func (x *GetTransceiverPowerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CanService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransceiverPowerResponse.ProtoReflect.Descriptor instead.
func (*GetTransceiverPowerResponse) Descriptor() ([]byte, []int) {
	return file_CanService_proto_rawDescGZIP(), []int{5}
}

func (x *GetTransceiverPowerResponse) GetPowerOn() bool {
	if x != nil {
		return x.PowerOn
	}
	return false
}

// Response containing status of a CAN termination pin
type GetTerminationResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TerminationEnabled bool                   `protobuf:"varint,1,opt,name=terminationEnabled,proto3" json:"terminationEnabled,omitempty"` // true if enabled, otherwise false
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetTerminationResponse) Reset() {
	*x = GetTerminationResponse{}
	mi := &file_CanService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTerminationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTerminationResponse) ProtoMessage() {}

func (x *GetTerminationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CanService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTerminationResponse.ProtoReflect.Descriptor instead.
func (*GetTerminationResponse) Descriptor() ([]byte, []int) {
	return file_CanService_proto_rawDescGZIP(), []int{6}
}

func (x *GetTerminationResponse) GetTerminationEnabled() bool {
	if x != nil {
		return x.TerminationEnabled
	}
	return false
}

// Response containing the statistics of a CAN interface
type GetStatisticsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RxPackets         uint64                 `protobuf:"varint,1,opt,name=RxPackets,proto3" json:"RxPackets,omitempty"`
	TxPackets         uint64                 `protobuf:"varint,2,opt,name=TxPackets,proto3" json:"TxPackets,omitempty"`
	RxBytes           uint64                 `protobuf:"varint,3,opt,name=RxBytes,proto3" json:"RxBytes,omitempty"`
	TxBytes           uint64                 `protobuf:"varint,4,opt,name=TxBytes,proto3" json:"TxBytes,omitempty"`
	RxErrors          uint64                 `protobuf:"varint,5,opt,name=RxErrors,proto3" json:"RxErrors,omitempty"`
	TxErrors          uint64                 `protobuf:"varint,6,opt,name=TxErrors,proto3" json:"TxErrors,omitempty"`
	RxDropped         uint64                 `protobuf:"varint,7,opt,name=RxDropped,proto3" json:"RxDropped,omitempty"`
	TxDropped         uint64                 `protobuf:"varint,8,opt,name=TxDropped,proto3" json:"TxDropped,omitempty"`
	Multicast         uint64                 `protobuf:"varint,9,opt,name=Multicast,proto3" json:"Multicast,omitempty"`
	Collisions        uint64                 `protobuf:"varint,10,opt,name=Collisions,proto3" json:"Collisions,omitempty"`
	RxLengthErrors    uint64                 `protobuf:"varint,11,opt,name=RxLengthErrors,proto3" json:"RxLengthErrors,omitempty"`
	RxOverErrors      uint64                 `protobuf:"varint,12,opt,name=RxOverErrors,proto3" json:"RxOverErrors,omitempty"`
	RxCrcErrors       uint64                 `protobuf:"varint,13,opt,name=RxCrcErrors,proto3" json:"RxCrcErrors,omitempty"`
	RxFrameErrors     uint64                 `protobuf:"varint,14,opt,name=RxFrameErrors,proto3" json:"RxFrameErrors,omitempty"`
	RxFifoErrors      uint64                 `protobuf:"varint,15,opt,name=RxFifoErrors,proto3" json:"RxFifoErrors,omitempty"`
	RxMissedErrors    uint64                 `protobuf:"varint,16,opt,name=RxMissedErrors,proto3" json:"RxMissedErrors,omitempty"`
	TxAbortedErrors   uint64                 `protobuf:"varint,17,opt,name=TxAbortedErrors,proto3" json:"TxAbortedErrors,omitempty"`
	TxCarrierErrors   uint64                 `protobuf:"varint,18,opt,name=TxCarrierErrors,proto3" json:"TxCarrierErrors,omitempty"`
	TxFifoErrors      uint64                 `protobuf:"varint,19,opt,name=TxFifoErrors,proto3" json:"TxFifoErrors,omitempty"`
	TxHeartbeatErrors uint64                 `protobuf:"varint,20,opt,name=TxHeartbeatErrors,proto3" json:"TxHeartbeatErrors,omitempty"`
	TxWindowErrors    uint64                 `protobuf:"varint,21,opt,name=TxWindowErrors,proto3" json:"TxWindowErrors,omitempty"`
	RxCompressed      uint64                 `protobuf:"varint,22,opt,name=RxCompressed,proto3" json:"RxCompressed,omitempty"`
	TxCompressed      uint64                 `protobuf:"varint,23,opt,name=TxCompressed,proto3" json:"TxCompressed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetStatisticsResponse) Reset() {
	*x = GetStatisticsResponse{}
	mi := &file_CanService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatisticsResponse) ProtoMessage() {}

func (x *GetStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CanService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_CanService_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatisticsResponse) GetRxPackets() uint64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *GetStatisticsResponse) GetTxPackets() uint64 {
	if x != nil {
		return x.TxPackets
	}
	return 0
}

func (x *GetStatisticsResponse) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *GetStatisticsResponse) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *GetStatisticsResponse) GetRxErrors() uint64 {
	if x != nil {
		return x.RxErrors
	}
	return 0
}

func (x *GetStatisticsResponse) GetTxErrors() uint64 {
	if x != nil {
		return x.TxErrors
	}
	return 0
}

func (x *GetStatisticsResponse) GetRxDropped() uint64 {
	if x != nil {
		return x.RxDropped
	}
	return 0
}

func (x *GetStatisticsResponse) GetTxDropped() uint64 {
	if x != nil {
		return x.TxDropped
	}
	return 0
}

func (x *GetStatisticsResponse) GetMulticast() uint64 {
	if x != nil {
		return x.Multicast
	}
	return 0
}

func (x *GetStatisticsResponse) GetCollisions() uint64 {
	if x != nil {
		return x.Collisions
	}
	return 0
}

func (x *GetStatisticsResponse) GetRxLengthErrors() uint64 {
	if x != nil {
		return x.RxLengthErrors
	}
	return 0
}

func (x *GetStatisticsResponse) GetRxOverErrors() uint64 {
	if x != nil {
		return x.RxOverErrors
	}
	return 0
}

func (x *GetStatisticsResponse) GetRxCrcErrors() uint64 {
	if x != nil {
		return x.RxCrcErrors
	}
	return 0
}

func (x *GetStatisticsResponse) GetRxFrameErrors() uint64 {
	if x != nil {
		return x.RxFrameErrors
	}
	return 0
}

func (x *GetStatisticsResponse) GetRxFifoErrors() uint64 {
	if x != nil {
		return x.RxFifoErrors
	}
	return 0
}

func (x *GetStatisticsResponse) GetRxMissedErrors() uint64 {
	if x != nil {
		return x.RxMissedErrors
	}
	return 0
}

func (x *GetStatisticsResponse) GetTxAbortedErrors() uint64 {
	if x != nil {
		return x.TxAbortedErrors
	}
	return 0
}

func (x *GetStatisticsResponse) GetTxCarrierErrors() uint64 {
	if x != nil {
		return x.TxCarrierErrors
	}
	return 0
}

func (x *GetStatisticsResponse) GetTxFifoErrors() uint64 {
	if x != nil {
		return x.TxFifoErrors
	}
	return 0
}

func (x *GetStatisticsResponse) GetTxHeartbeatErrors() uint64 {
	if x != nil {
		return x.TxHeartbeatErrors
	}
	return 0
}

func (x *GetStatisticsResponse) GetTxWindowErrors() uint64 {
	if x != nil {
		return x.TxWindowErrors
	}
	return 0
}

func (x *GetStatisticsResponse) GetRxCompressed() uint64 {
	if x != nil {
		return x.RxCompressed
	}
	return 0
}

func (x *GetStatisticsResponse) GetTxCompressed() uint64 {
	if x != nil {
		return x.TxCompressed
	}
	return 0
}

// Response containing the bitrate of a CAN interface
type GetBitrateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bitrate       uint32                 `protobuf:"varint,1,opt,name=bitrate,proto3" json:"bitrate,omitempty"` // Number of transmitted frames
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBitrateResponse) Reset() {
	*x = GetBitrateResponse{}
	mi := &file_CanService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBitrateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBitrateResponse) ProtoMessage() {}

func (x *GetBitrateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CanService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBitrateResponse.ProtoReflect.Descriptor instead.
func (*GetBitrateResponse) Descriptor() ([]byte, []int) {
	return file_CanService_proto_rawDescGZIP(), []int{8}
}

func (x *GetBitrateResponse) GetBitrate() uint32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

// Response containing the bitrate of a CAN interface
type GetBusStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         BusStates              `protobuf:"varint,1,opt,name=state,proto3,enum=hal.can.BusStates" json:"state,omitempty"` // Number of transmitted frames
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBusStateResponse) Reset() {
	*x = GetBusStateResponse{}
	mi := &file_CanService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBusStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusStateResponse) ProtoMessage() {}

func (x *GetBusStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CanService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusStateResponse.ProtoReflect.Descriptor instead.
func (*GetBusStateResponse) Descriptor() ([]byte, []int) {
	return file_CanService_proto_rawDescGZIP(), []int{9}
}

func (x *GetBusStateResponse) GetState() BusStates {
	if x != nil {
		return x.State
	}
	return BusStates_ERROR_ACTIVE
}

// Request containing parameters for SetInterfaceToContainer method
type SetInterfaceToContainerRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName       string                 `protobuf:"bytes,1,opt,name=interfaceName,proto3" json:"interfaceName,omitempty"`             // e.g., "CAN1"
	DockerContainerName string                 `protobuf:"bytes,2,opt,name=dockerContainerName,proto3" json:"dockerContainerName,omitempty"` // e.g., "app-engine", leave empty to move to host
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SetInterfaceToContainerRequest) Reset() {
	*x = SetInterfaceToContainerRequest{}
	mi := &file_CanService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetInterfaceToContainerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInterfaceToContainerRequest) ProtoMessage() {}

func (x *SetInterfaceToContainerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_CanService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInterfaceToContainerRequest.ProtoReflect.Descriptor instead.
func (*SetInterfaceToContainerRequest) Descriptor() ([]byte, []int) {
	return file_CanService_proto_rawDescGZIP(), []int{10}
}

func (x *SetInterfaceToContainerRequest) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *SetInterfaceToContainerRequest) GetDockerContainerName() string {
	if x != nil {
		return x.DockerContainerName
	}
	return ""
}

// Represents a mapping of interface to docker container
type InterfaceToContainerMapping struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName       string                 `protobuf:"bytes,1,opt,name=interfaceName,proto3" json:"interfaceName,omitempty"`             // e.g., "CAN1"
	DockerContainerName string                 `protobuf:"bytes,2,opt,name=dockerContainerName,proto3" json:"dockerContainerName,omitempty"` // e.g., "app-engine", if empty string then interface is mapped to host
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InterfaceToContainerMapping) Reset() {
	*x = InterfaceToContainerMapping{}
	mi := &file_CanService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceToContainerMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceToContainerMapping) ProtoMessage() {}

func (x *InterfaceToContainerMapping) ProtoReflect() protoreflect.Message {
	mi := &file_CanService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceToContainerMapping.ProtoReflect.Descriptor instead.
func (*InterfaceToContainerMapping) Descriptor() ([]byte, []int) {
	return file_CanService_proto_rawDescGZIP(), []int{11}
}

func (x *InterfaceToContainerMapping) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *InterfaceToContainerMapping) GetDockerContainerName() string {
	if x != nil {
		return x.DockerContainerName
	}
	return ""
}

// Response contains mapping of interfaces to docker containers
type GetInterfaceToContainerMappingResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Items         []*InterfaceToContainerMapping `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"` // List of interface to docker container mappings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInterfaceToContainerMappingResponse) Reset() {
	*x = GetInterfaceToContainerMappingResponse{}
	mi := &file_CanService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInterfaceToContainerMappingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInterfaceToContainerMappingResponse) ProtoMessage() {}

func (x *GetInterfaceToContainerMappingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_CanService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInterfaceToContainerMappingResponse.ProtoReflect.Descriptor instead.
func (*GetInterfaceToContainerMappingResponse) Descriptor() ([]byte, []int) {
	return file_CanService_proto_rawDescGZIP(), []int{12}
}

func (x *GetInterfaceToContainerMappingResponse) GetItems() []*InterfaceToContainerMapping {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_CanService_proto protoreflect.FileDescriptor

const file_CanService_proto_rawDesc = "" +
	"\n" +
	"\x10CanService.proto\x12\ahal.can\x1a\x1bgoogle/protobuf/empty.proto\"\\\n" +
	"\x1aSetTransceiverPowerRequest\x12$\n" +
	"\rinterfaceName\x18\x01 \x01(\tR\rinterfaceName\x12\x18\n" +
	"\apowerOn\x18\x02 \x01(\bR\apowerOn\"k\n" +
	"\x15SetTerminationRequest\x12$\n" +
	"\rinterfaceName\x18\x01 \x01(\tR\rinterfaceName\x12,\n" +
	"\x11enableTermination\x18\x02 \x01(\bR\x11enableTermination\"\x17\n" +
	"\x15ListInterfacesRequest\"8\n" +
	"\x16ListInterfacesResponse\x12\x1e\n" +
	"\n" +
	"interfaces\x18\x01 \x03(\tR\n" +
	"interfaces\"?\n" +
	"\x17GetInterfaceNameRequest\x12$\n" +
	"\rinterfaceName\x18\x01 \x01(\tR\rinterfaceName\"7\n" +
	"\x1bGetTransceiverPowerResponse\x12\x18\n" +
	"\apowerOn\x18\x01 \x01(\bR\apowerOn\"H\n" +
	"\x16GetTerminationResponse\x12.\n" +
	"\x12terminationEnabled\x18\x01 \x01(\bR\x12terminationEnabled\"\xaf\x06\n" +
	"\x15GetStatisticsResponse\x12\x1c\n" +
	"\tRxPackets\x18\x01 \x01(\x04R\tRxPackets\x12\x1c\n" +
	"\tTxPackets\x18\x02 \x01(\x04R\tTxPackets\x12\x18\n" +
	"\aRxBytes\x18\x03 \x01(\x04R\aRxBytes\x12\x18\n" +
	"\aTxBytes\x18\x04 \x01(\x04R\aTxBytes\x12\x1a\n" +
	"\bRxErrors\x18\x05 \x01(\x04R\bRxErrors\x12\x1a\n" +
	"\bTxErrors\x18\x06 \x01(\x04R\bTxErrors\x12\x1c\n" +
	"\tRxDropped\x18\a \x01(\x04R\tRxDropped\x12\x1c\n" +
	"\tTxDropped\x18\b \x01(\x04R\tTxDropped\x12\x1c\n" +
	"\tMulticast\x18\t \x01(\x04R\tMulticast\x12\x1e\n" +
	"\n" +
	"Collisions\x18\n" +
	" \x01(\x04R\n" +
	"Collisions\x12&\n" +
	"\x0eRxLengthErrors\x18\v \x01(\x04R\x0eRxLengthErrors\x12\"\n" +
	"\fRxOverErrors\x18\f \x01(\x04R\fRxOverErrors\x12 \n" +
	"\vRxCrcErrors\x18\r \x01(\x04R\vRxCrcErrors\x12$\n" +
	"\rRxFrameErrors\x18\x0e \x01(\x04R\rRxFrameErrors\x12\"\n" +
	"\fRxFifoErrors\x18\x0f \x01(\x04R\fRxFifoErrors\x12&\n" +
	"\x0eRxMissedErrors\x18\x10 \x01(\x04R\x0eRxMissedErrors\x12(\n" +
	"\x0fTxAbortedErrors\x18\x11 \x01(\x04R\x0fTxAbortedErrors\x12(\n" +
	"\x0fTxCarrierErrors\x18\x12 \x01(\x04R\x0fTxCarrierErrors\x12\"\n" +
	"\fTxFifoErrors\x18\x13 \x01(\x04R\fTxFifoErrors\x12,\n" +
	"\x11TxHeartbeatErrors\x18\x14 \x01(\x04R\x11TxHeartbeatErrors\x12&\n" +
	"\x0eTxWindowErrors\x18\x15 \x01(\x04R\x0eTxWindowErrors\x12\"\n" +
	"\fRxCompressed\x18\x16 \x01(\x04R\fRxCompressed\x12\"\n" +
	"\fTxCompressed\x18\x17 \x01(\x04R\fTxCompressed\".\n" +
	"\x12GetBitrateResponse\x12\x18\n" +
	"\abitrate\x18\x01 \x01(\rR\abitrate\"?\n" +
	"\x13GetBusStateResponse\x12(\n" +
	"\x05state\x18\x01 \x01(\x0e2\x12.hal.can.BusStatesR\x05state\"x\n" +
	"\x1eSetInterfaceToContainerRequest\x12$\n" +
	"\rinterfaceName\x18\x01 \x01(\tR\rinterfaceName\x120\n" +
	"\x13dockerContainerName\x18\x02 \x01(\tR\x13dockerContainerName\"u\n" +
	"\x1bInterfaceToContainerMapping\x12$\n" +
	"\rinterfaceName\x18\x01 \x01(\tR\rinterfaceName\x120\n" +
	"\x13dockerContainerName\x18\x02 \x01(\tR\x13dockerContainerName\"d\n" +
	"&GetInterfaceToContainerMappingResponse\x12:\n" +
	"\x05items\x18\x01 \x03(\v2$.hal.can.InterfaceToContainerMappingR\x05items*k\n" +
	"\tBusStates\x12\x10\n" +
	"\fERROR_ACTIVE\x10\x00\x12\x11\n" +
	"\rERROR_WARNING\x10\x01\x12\x11\n" +
	"\rERROR_PASSIVE\x10\x02\x12\v\n" +
	"\aBUS_OFF\x10\x03\x12\v\n" +
	"\aSTOPPED\x10\x04\x12\f\n" +
	"\bSLEEPING\x10\x052\xf0\x06\n" +
	"\x03Can\x12]\n" +
	"\x13GetTransceiverPower\x12 .hal.can.GetInterfaceNameRequest\x1a$.hal.can.GetTransceiverPowerResponse\x12S\n" +
	"\x0eGetTermination\x12 .hal.can.GetInterfaceNameRequest\x1a\x1f.hal.can.GetTerminationResponse\x12T\n" +
	"\x13SetTransceiverPower\x12#.hal.can.SetTransceiverPowerRequest\x1a\x16.google.protobuf.Empty\"\x00\x12J\n" +
	"\x0eSetTermination\x12\x1e.hal.can.SetTerminationRequest\x1a\x16.google.protobuf.Empty\"\x00\x12S\n" +
	"\x0eListInterfaces\x12\x1e.hal.can.ListInterfacesRequest\x1a\x1f.hal.can.ListInterfacesResponse\"\x00\x12S\n" +
	"\rGetStatistics\x12 .hal.can.GetInterfaceNameRequest\x1a\x1e.hal.can.GetStatisticsResponse\"\x00\x12M\n" +
	"\n" +
	"GetBitrate\x12 .hal.can.GetInterfaceNameRequest\x1a\x1b.hal.can.GetBitrateResponse\"\x00\x12O\n" +
	"\vGetBusState\x12 .hal.can.GetInterfaceNameRequest\x1a\x1c.hal.can.GetBusStateResponse\"\x00\x12\\\n" +
	"\x17SetInterfaceToContainer\x12'.hal.can.SetInterfaceToContainerRequest\x1a\x16.google.protobuf.Empty\"\x00\x12k\n" +
	"\x1eGetInterfaceToContainerMapping\x12\x16.google.protobuf.Empty\x1a/.hal.can.GetInterfaceToContainerMappingResponse\"\x00B\x11Z\x0f./protos;protosb\x06proto3"

var (
	file_CanService_proto_rawDescOnce sync.Once
	file_CanService_proto_rawDescData []byte
)

func file_CanService_proto_rawDescGZIP() []byte {
	file_CanService_proto_rawDescOnce.Do(func() {
		file_CanService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_CanService_proto_rawDesc), len(file_CanService_proto_rawDesc)))
	})
	return file_CanService_proto_rawDescData
}

var file_CanService_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_CanService_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_CanService_proto_goTypes = []any{
	(BusStates)(0),                                 // 0: hal.can.BusStates
	(*SetTransceiverPowerRequest)(nil),             // 1: hal.can.SetTransceiverPowerRequest
	(*SetTerminationRequest)(nil),                  // 2: hal.can.SetTerminationRequest
	(*ListInterfacesRequest)(nil),                  // 3: hal.can.ListInterfacesRequest
	(*ListInterfacesResponse)(nil),                 // 4: hal.can.ListInterfacesResponse
	(*GetInterfaceNameRequest)(nil),                // 5: hal.can.GetInterfaceNameRequest
	(*GetTransceiverPowerResponse)(nil),            // 6: hal.can.GetTransceiverPowerResponse
	(*GetTerminationResponse)(nil),                 // 7: hal.can.GetTerminationResponse
	(*GetStatisticsResponse)(nil),                  // 8: hal.can.GetStatisticsResponse
	(*GetBitrateResponse)(nil),                     // 9: hal.can.GetBitrateResponse
	(*GetBusStateResponse)(nil),                    // 10: hal.can.GetBusStateResponse
	(*SetInterfaceToContainerRequest)(nil),         // 11: hal.can.SetInterfaceToContainerRequest
	(*InterfaceToContainerMapping)(nil),            // 12: hal.can.InterfaceToContainerMapping
	(*GetInterfaceToContainerMappingResponse)(nil), // 13: hal.can.GetInterfaceToContainerMappingResponse
	(*emptypb.Empty)(nil),                          // 14: google.protobuf.Empty
}
var file_CanService_proto_depIdxs = []int32{
	0,  // 0: hal.can.GetBusStateResponse.state:type_name -> hal.can.BusStates
	12, // 1: hal.can.GetInterfaceToContainerMappingResponse.items:type_name -> hal.can.InterfaceToContainerMapping
	5,  // 2: hal.can.Can.GetTransceiverPower:input_type -> hal.can.GetInterfaceNameRequest
	5,  // 3: hal.can.Can.GetTermination:input_type -> hal.can.GetInterfaceNameRequest
	1,  // 4: hal.can.Can.SetTransceiverPower:input_type -> hal.can.SetTransceiverPowerRequest
	2,  // 5: hal.can.Can.SetTermination:input_type -> hal.can.SetTerminationRequest
	3,  // 6: hal.can.Can.ListInterfaces:input_type -> hal.can.ListInterfacesRequest
	5,  // 7: hal.can.Can.GetStatistics:input_type -> hal.can.GetInterfaceNameRequest
	5,  // 8: hal.can.Can.GetBitrate:input_type -> hal.can.GetInterfaceNameRequest
	5,  // 9: hal.can.Can.GetBusState:input_type -> hal.can.GetInterfaceNameRequest
	11, // 10: hal.can.Can.SetInterfaceToContainer:input_type -> hal.can.SetInterfaceToContainerRequest
	14, // 11: hal.can.Can.GetInterfaceToContainerMapping:input_type -> google.protobuf.Empty
	6,  // 12: hal.can.Can.GetTransceiverPower:output_type -> hal.can.GetTransceiverPowerResponse
	7,  // 13: hal.can.Can.GetTermination:output_type -> hal.can.GetTerminationResponse
	14, // 14: hal.can.Can.SetTransceiverPower:output_type -> google.protobuf.Empty
	14, // 15: hal.can.Can.SetTermination:output_type -> google.protobuf.Empty
	4,  // 16: hal.can.Can.ListInterfaces:output_type -> hal.can.ListInterfacesResponse
	8,  // 17: hal.can.Can.GetStatistics:output_type -> hal.can.GetStatisticsResponse
	9,  // 18: hal.can.Can.GetBitrate:output_type -> hal.can.GetBitrateResponse
	10, // 19: hal.can.Can.GetBusState:output_type -> hal.can.GetBusStateResponse
	14, // 20: hal.can.Can.SetInterfaceToContainer:output_type -> google.protobuf.Empty
	13, // 21: hal.can.Can.GetInterfaceToContainerMapping:output_type -> hal.can.GetInterfaceToContainerMappingResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_CanService_proto_init() }
func file_CanService_proto_init() {
	if File_CanService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_CanService_proto_rawDesc), len(file_CanService_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_CanService_proto_goTypes,
		DependencyIndexes: file_CanService_proto_depIdxs,
		EnumInfos:         file_CanService_proto_enumTypes,
		MessageInfos:      file_CanService_proto_msgTypes,
	}.Build()
	File_CanService_proto = out.File
	file_CanService_proto_goTypes = nil
	file_CanService_proto_depIdxs = nil
}
